### PR TITLE
Copied MPIRPC into Hapbin

### PR DESCRIPTION
**Pull request by camaclean**
By copying in MPIRPC, Hapbin no longer requires additional steps to get working without root access.

Also added documentation for compiling with a non-default toolchain (compiler, binutils, libraries, etc.).

### CODE REVIEW

**Comment by npch** [comment]
Thanks Colin - going to try this out and check it works on a clean install, then merge.

**Comment by npch** [comment]
I attempted an install on a vanilla Ubuntu 14.04 system using sudo.

I installed gcc 4.8.2-19ubuntu1 via the build-essentials package (also installs g++ and make which are required by CMake).
I had to install CMake 3.2.3 separately as it is not included in build-essentials.
(Note: the CMake installation instructions are not user friendly - we might consider walking people through this for now)

hapbin executables built without errors without any other dependencies. So MPIRPC inclusion works.

I tried the example command given in the README, but this referred to a phasedHaplotype .hap file that is not included in the repository. Likewise, the expected outputs from running these examples should be included in the repository to enable users to do a rudimentary verification that the executables have been built correctly. I've raised issue #10 to fix this.

**Comment by npch** [comment]
I also confirm that with the prerequisites of gcc, make, and CMake I am able to build using a user account without requiring sudo privileges.

**Comment by camaclean** [comment]
Does the cmake package in Ubuntu not work for you? It could be that the version in LTS isn't new enough. If I remove the unit tests (which don't test for much at this point, a lot got removed with the removal of the bit vector classes), I can get the cmake requirements down.

**Comment by npch** [comment]
Short answer: just tried, it works.

Long answer:

I went straight to the CMake website on the original test run because the CMake package isn't installed by default in the general "build-essential" package on Ubuntu.

However using:

apt-get update
apt-get install build-essential
apt-get install cmake

will install all prerequisites on Ubuntu 14.04 (installing gcc 4.8.2 and cmake 2.8.12.2 at the time of writing).

Testing in user mode and I was able to successfully build the hapbin executables.

I'd suggest updating the README to provide instructions for different common operating systems, if we're not going to distribute precompiled binaries.

**Comment by prenderj** [comment]
Hi

I tried installing hapbin on Red Hat Enterprise Linux 7.1, SUSE Linux
Enterprise Server 12 and Ubuntu Server 14.04 LTS. Adding MPIRPC makes it a
lot simpler. Didnt have any problems with ubuntu and SUSE (will add SUSE to
README) but got the problem with cmake version on red hat:

sudo yum install cmake
git clone https://github.com/evotools/hapbin.git
cd hapbin/build/
cmake ../src/

CMake Error at CMakeLists.txt:18 (cmake_minimum_required):
CMake 2.8.12 or higher is required.  You are running version 2.8.11


So it will be good if we can lower this requirement. Including precompiled
binaries I think is a good idea. The ubuntu binary works on red hat without
needing to install any packages.

**Comment by camaclean** [comment]
The problem with precompiled binaries on Linux is that many versions are required. You cannot compile against a newer version of glibc and then run an application on a system with an older glibc (and sometimes a newer glibc). This typically means providing a package for each distro. Then, for each distro, we have three MPI options: no MPI, MPICH, and OpenMPI. It's pretty easy to cross compile Windows binaries, though. This is why I like running Gentoo, where everything is built from source and these library issues either don't exist or are easy to fix.

-------- Original message --------

**Comment by prenderj** [comment]
Ok. If we can lower the cmake this will likely make linux installs simpler.
Are you happy we lower this in CMakeLists.txt? Testing framework is
unlikely to be relevant to most users so if this is only issue then
probably makes sense to do this.

**Pull request merged**
